### ISSUE TITLE
header concatenation

### ISSUE THREAD

**Issue by MelanieGault** [cernops/puppet-motd#5]
Hi,

I'm looking for a motd module and yours seems interesting.
There is something I would like to do and I'm not sure how the module handle this:

I need a header for legal stuff for all my servers (conf located in global.yaml)
I also need for each server some specific data. (conf located in srvname.yaml)

If I set in my global.yaml

```
motd_header:
   - commonstuff
   - Legalstuff
```

and in my srvname.yaml

```
motd_header:
   - specific stuff
```

both motd_header will be concatenated or only on will be used ?

Thanks!

Mélanie

**Comment by traylenator** [comment]
Hi @MelanieGault 

Only the first one will display.

I would do this.

In hiera 

``` yaml
motd::header:
  - legal stuff
 -  other stuff
```

and in puppet manifest itself.

``` puppet
inlcude ::motd

motd::header{"This is node ${::fqdn}":}
```

Does that work for you?

**Comment by MelanieGault** [comment]
Hi,

Thanks for this very fast answer !

I have lot of specific lines (between 5 and 30) but I think mixing hiera and manifest should be OK.
General stuff in hiera and specific stuff in profile manifests... I will give it a try tomorrow !

Another question with that, how the order of header line are managed ?

Thanks a lot !
Mélanie

**Comment by traylenator** [comment]
``` puppet
motd::header{'My first header':
   message => 'This is a really great computer',
   order      => '02;
}
motd::header{'My first header':
   message => 'This is a really great computer',
   order      => '03';
}

```

by default order is '05' on these headers.

The module is thin wrapper around concat basically so uss the same mechanism as that.

The really useful feature of the module is the date stamped news items which archive
by themselves.

Steve.

**Comment by MelanieGault** [comment]
hi,
It works fine with legal and common multiline in hiera and explicite resource in profiles manifests.

Thanks.
Mélanie
